import { DEFAULT_CAPTION_STYLE, type CaptionStyle } from "./schema";

function preset(
  id: string,
  name: string,
  category: CaptionStyle["category"],
  over: Partial<CaptionStyle>
): CaptionStyle {
  return { id, name, category, ...DEFAULT_CAPTION_STYLE, ...over } as CaptionStyle;
}

export const PRESETS: CaptionStyle[] = [
  // ─── Content Aware ───────────────────────────────────────────
  preset("ca-hormozi", "Hormozi", "contentAware", {
    font: "Inter",
    size: 0.085,
    letterCasing: "uppercase",
    color: "#ffffff",
    animation: "highlight",
    animationColor: "#FFE600",
    autoHighlightEnabled: true,
    autoHighlightStyles: { bold: true, color: "#FFE600", italic: false, spacing: 2 },
    outline: { color: "#000000", width: 10 },
    shadow: { color: "#000000", blur: 0, offsetX: 0, offsetY: 6 },
  }),
  preset("ca-iman", "Iman Gadzhi", "contentAware", {
    font: "Epilogue",
    size: 0.075,
    color: "#ffffff",
    animation: "reveal",
    autoHighlightEnabled: true,
    autoHighlightStyles: { bold: true, color: "#21E06B", italic: false, spacing: 0 },
    outline: { color: "#000000", width: 8 },
  }),
  preset("ca-subtle", "Subtle", "contentAware", {
    font: "Epilogue",
    size: 0.055,
    animation: "none",
    color: "#ffffff",
    background: {
      type: "block",
      color: "#00000099",
      cornerRadius: { topLeft: 8, topRight: 8, bottomLeft: 8, bottomRight: 8 },
      innerPadding: { top: 6, right: 14, bottom: 6, left: 14 },
    },
    outline: null,
    shadow: null,
  }),

  // ─── Dynamic ─────────────────────────────────────────────────
  preset("dy-popin", "Pop In", "dynamic", {
    font: "Epilogue",
    size: 0.09,
    letterCasing: "uppercase",
    animation: "impactPop",
    animationColor: "#FF3366",
    outline: { color: "#000000", width: 10 },
  }),
  preset("dy-float", "Float Up", "dynamic", {
    font: "Epilogue",
    size: 0.08,
    animation: "floatInUp",
    color: "#ffffff",
    outline: { color: "#000000", width: 8 },
  }),
  preset("dy-drop", "Drop In", "dynamic", {
    font: "Epilogue",
    size: 0.09,
    letterCasing: "uppercase",
    animation: "dropIn",
    color: "#ffffff",
    outline: { color: "#000000", width: 10 },
  }),
  preset("dy-karaoke", "Karaoke", "dynamic", {
    font: "Epilogue",
    size: 0.08,
    animation: "karaoke",
    animationColor: "#00D1FF",
    color: "#ffffff",
    outline: { color: "#000000", width: 8 },
  }),

  // ─── Social ──────────────────────────────────────────────────
  preset("so-tiktok", "TikTok White", "social", {
    font: "Inter",
    size: 0.07,
    color: "#ffffff",
    animation: "scaleIn",
    background: {
      type: "word",
      color: "#000000",
      cornerRadius: { topLeft: 6, topRight: 6, bottomLeft: 6, bottomRight: 6 },
      innerPadding: { top: 4, right: 10, bottom: 4, left: 10 },
    },
    outline: null,
    shadow: null,
  }),
  preset("so-reels", "Reels Bold", "social", {
    font: "Epilogue",
    size: 0.09,
    letterCasing: "uppercase",
    animation: "boxHighlight",
    animationColor: "#FF2D55",
    color: "#ffffff",
    outline: { color: "#000000", width: 8 },
  }),
  preset("so-shorts", "Shorts Pop", "social", {
    font: "Epilogue",
    size: 0.09,
    animation: "impact",
    color: "#FFE600",
    outline: { color: "#000000", width: 12 },
  }),

  // ─── Business ────────────────────────────────────────────────
  preset("bu-clean", "Clean Broadcast", "business", {
    font: "Epilogue",
    size: 0.05,
    color: "#ffffff",
    animation: "none",
    background: {
      type: "block",
      color: "#000000CC",
      cornerRadius: { topLeft: 4, topRight: 4, bottomLeft: 4, bottomRight: 4 },
      innerPadding: { top: 8, right: 16, bottom: 8, left: 16 },
    },
    outline: null,
    shadow: null,
  }),
  preset("bu-podcast", "Podcast", "business", {
    font: "Epilogue",
    size: 0.06,
    color: "#E5E5E5",
    animation: "highlight",
    animationColor: "#3B82F6",
    autoHighlightEnabled: true,
    autoHighlightStyles: { bold: true, color: "#3B82F6", italic: false, spacing: 0 },
    outline: { color: "#000000", width: 6 },
  }),
  preset("bu-news", "News Lower", "business", {
    font: "Epilogue",
    size: 0.045,
    y: 0.9,
    color: "#ffffff",
    animation: "none",
    background: {
      type: "block",
      color: "#CC0000",
      cornerRadius: { topLeft: 0, topRight: 0, bottomLeft: 0, bottomRight: 0 },
      innerPadding: { top: 8, right: 20, bottom: 8, left: 20 },
    },
    outline: null,
    shadow: null,
  }),

  // ─── Retro ───────────────────────────────────────────────────
  preset("re-80s", "80s Neon", "retro", {
    font: "Epilogue",
    size: 0.085,
    letterCasing: "uppercase",
    color: "#FF00E5",
    animation: "rotateFlip",
    outline: { color: "#00F0FF", width: 6 },
    shadow: { color: "#FF00E5", blur: 20, offsetX: 0, offsetY: 0 },
  }),
  preset("re-vhs", "VHS", "retro", {
    font: "Epilogue",
    size: 0.08,
    letterCasing: "uppercase",
    color: "#F2F2F2",
    animation: "flipClock",
    outline: { color: "#111111", width: 8 },
    shadow: { color: "#FF0040", blur: 0, offsetX: 4, offsetY: 0 },
  }),
  preset("re-paper", "Paper", "retro", {
    font: "Epilogue",
    size: 0.07,
    color: "#1a1a1a",
    animation: "stack",
    background: {
      type: "block",
      color: "#F5EFDC",
      cornerRadius: { topLeft: 4, topRight: 4, bottomLeft: 4, bottomRight: 4 },
      innerPadding: { top: 10, right: 18, bottom: 10, left: 18 },
    },
    outline: null,
    shadow: { color: "#00000066", blur: 10, offsetX: 4, offsetY: 6 },
  }),

  // ─── Creator (named) ─────────────────────────────────────────
  preset("cr-iman", "Iman", "creator", {
    font: "Satoshi",
    size: 0.072,
    letterCasing: "lowercase",
    color: "#ffffff",
    animation: "weightMorph",
    animationColor: "#ffffff",
    autoHighlightEnabled: false,
    outline: { color: "#000000", width: 4 },
    shadow: { color: "#00000088", blur: 8, offsetX: 0, offsetY: 3 },
    strokeRatio: 1 / 14,
  }),
  preset("cr-ali", "Ali Abdaal", "creator", {
    font: "General Sans",
    size: 0.065,
    letterCasing: "normal",
    color: "#ffffff",
    animation: "underlineSweep",
    animationColor: "#FFD84C",
    underlineColor: "#FFD84C",
    autoHighlightEnabled: true,
    autoHighlightStyles: { bold: true, color: "#FFD84C", italic: false, spacing: 0 },
    outline: null,
    shadow: { color: "#00000099", blur: 10, offsetX: 0, offsetY: 3 },
  }),
  preset("cr-devin", "Devin", "creator", {
    font: "Clash Display",
    size: 0.082,
    letterCasing: "uppercase",
    color: "#ffffff",
    animation: "colorCycle",
    animationColor: "#FFD84C",
    accentPalette: ["#FFFFFF", "#FFD84C", "#39D7FF", "#FF4D8D", "#A4FF3B"],
    colorCycleHz: 6,
    outline: { color: "#000000", width: 8 },
    shadow: { color: "#000000CC", blur: 0, offsetX: 0, offsetY: 4 },
  }),
  preset("cr-beast", "Beast", "creator", {
    font: "Bangers",
    size: 0.095,
    letterCasing: "uppercase",
    color: "#ffffff",
    animation: "impactPop",
    animationColor: "#00C853",
    autoHighlightEnabled: true,
    autoHighlightStyles: { bold: true, color: "#00C853", italic: false, spacing: 2 },
    outline: { color: "#000000", width: 12 },
    shadow: { color: "#000000", blur: 0, offsetX: 0, offsetY: 8 },
    strokeRatio: 1 / 10,
    rotationJitterDeg: 4,
    rotationRandomEnabled: true,
  }),
  preset("cr-hormozi-v2", "Hormozi v2", "creator", {
    font: "Cabinet Grotesk",
    size: 0.088,
    letterCasing: "uppercase",
    color: "#ffffff",
    animation: "impactPop",
    animationColor: "#FFD700",
    autoHighlightEnabled: true,
    autoHighlightStyles: { bold: true, color: "#FFD700", italic: false, spacing: 2 },
    outline: { color: "#000000", width: 10 },
    shadow: { color: "#000000", blur: 0, offsetX: 0, offsetY: 6 },
    strokeRatio: 1 / 11,
  }),

  // ─── Premium (craft tier) ────────────────────────────────────
  preset("pr-editorial", "Editorial Display", "premium", {
    font: "Playfair Display",
    size: 0.078,
    letterCasing: "capitalize",
    color: "#F2F2F2",
    emphasis: "italic",
    animation: "reveal",
    animationColor: "#F2F2F2",
    outline: null,
    shadow: { color: "#000000AA", blur: 18, offsetX: 0, offsetY: 4 },
  }),
  preset("pr-brutalist", "Brutalist Mono", "premium", {
    font: "JetBrains Mono",
    size: 0.062,
    letterCasing: "lowercase",
    color: "#ffffff",
    animation: "stomp",
    animationColor: "#000000",
    autoHighlightEnabled: true,
    autoHighlightStyles: { bold: true, color: "#000000", italic: false, spacing: 0 },
    background: {
      type: "word",
      color: "#000000",
      cornerRadius: { topLeft: 0, topRight: 0, bottomLeft: 0, bottomRight: 0 },
      innerPadding: { top: 4, right: 10, bottom: 4, left: 10 },
    },
    outline: null,
    shadow: null,
  }),
  preset("pr-aesthetic", "Aesthetic", "premium", {
    font: "Gambetta",
    size: 0.068,
    letterCasing: "lowercase",
    emphasis: "italic",
    color: "#F5EFE6",
    animation: "floatInUp",
    animationColor: "#F5EFE6",
    autoHighlightEnabled: true,
    autoHighlightStyles: { bold: false, color: "#D4AF37", italic: true, spacing: 0 },
    outline: null,
    shadow: { color: "#00000066", blur: 14, offsetX: 0, offsetY: 4 },
  }),
  preset("pr-chromatic", "Chromatic", "premium", {
    font: "Clash Display",
    size: 0.082,
    letterCasing: "uppercase",
    color: "#ffffff",
    animation: "chromaticSplit",
    animationColor: "#ffffff",
    chromaticOffsetPx: 3,
    outline: null,
    shadow: { color: "#000000AA", blur: 6, offsetX: 0, offsetY: 2 },
  }),
  preset("pr-glass", "Glass Pill", "premium", {
    font: "General Sans",
    size: 0.062,
    letterCasing: "normal",
    color: "#ffffff",
    animation: "glassPill",
    animationColor: "#ffffff",
    background: {
      type: "word",
      color: "#FFFFFF14",
      cornerRadius: { topLeft: 22, topRight: 22, bottomLeft: 22, bottomRight: 22 },
      innerPadding: { top: 8, right: 18, bottom: 8, left: 18 },
    },
    outline: null,
    shadow: { color: "#00000066", blur: 20, offsetX: 0, offsetY: 6 },
  }),
  preset("pr-typewriter", "Typewriter", "premium", {
    font: "JetBrains Mono",
    size: 0.058,
    letterCasing: "lowercase",
    color: "#ffffff",
    animation: "typewriterChar",
    animationColor: "#ffffff",
    typewriterStaggerMs: 30,
    outline: null,
    shadow: { color: "#000000AA", blur: 8, offsetX: 0, offsetY: 2 },
  }),
  preset("pr-karaoke-wipe", "Karaoke Wipe", "premium", {
    font: "Uncut Sans",
    size: 0.085,
    letterCasing: "uppercase",
    color: "#ffffff",
    animation: "boxHighlight",
    animationColor: "#FF2D55",
    outline: { color: "#000000", width: 6 },
    shadow: null,
  }),
  preset("pr-depth", "3D Stack", "premium", {
    font: "Nohemi",
    size: 0.088,
    letterCasing: "uppercase",
    color: "#ffffff",
    animation: "depthStack",
    animationColor: "#111111",
    secondaryColor: "#111111",
    depthStackCount: 3,
    outline: null,
    shadow: null,
  }),
];

export const PRESETS_BY_ID: Record<string, CaptionStyle> = Object.fromEntries(
  PRESETS.map((p) => [p.id, p])
);

export const CATEGORY_LABELS: Record<CaptionStyle["category"], string> = {
  contentAware: "Content Aware",
  dynamic: "Dynamic",
  social: "Social",
  business: "Business",
  retro: "Retro",
  creator: "Creator",
  premium: "Premium",
};
